---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: docker.io/ellenkorbes/router
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  # When using minikube, set the type to "NodePort"
  # When using Digital Ocean, set it to "LoadBalancer"
  type: NodePort
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 30085
    protocol: TCP
    name: http
  selector:
    app: router